export const data = {
    current_page: 1,
    data: [
        {
            id: '1',
            product_name: 'Shampoo Herbal',
            product_code: 'PRD-001',
            location: 'Gudang A > Ruang 1 > Rak 01 > Layer A',
            quantity: 120,
        },
        {
            id: '2',
            product_name: 'Sabun Cair',
            product_code: 'PRD-002',
            location: 'Gudang A > Ruang 1 > Rak 01 > Layer B',
            quantity: 75,
        },
        {
            id: '3',
            product_name: 'Face Wash',
            product_code: 'PRD-003',
            location: 'Gudang A > Ruang 2 > Rak 02 > Layer A',
            quantity: 50,
        },
        {
            id: '4',
            product_name: 'Body Lotion',
            product_code: 'PRD-004',
            location: 'Gudang A > Ruang 2 > Rak 02 > Layer B',
            quantity: 200,
        },
        {
            id: '5',
            product_name: 'Hair Oil',
            product_code: 'PRD-005',
            location: 'Gudang B > Ruang 1 > Rak 03 > Layer C',
            quantity: 90,
        },
    ],
    from: 1,
    last_page: 2,
    first_page_url: 'http://localhost/api/storage?page=1',
    last_page_url: 'http://localhost/api/storage?page=2',
    links: [
        { url: null, label: '&laquo; Previous', active: false },
        { url: 'http://localhost/api/storage?page=1', label: '1', active: true },
        { url: 'http://localhost/api/storage?page=2', label: '2', active: false },
        { url: 'http://localhost/api/storage?page=2', label: 'Next &raquo;', active: false },
    ],
    next_page_url: 'http://localhost/api/storage?page=2',
    path: 'http://localhost/api/storage',
    per_page: 5,
    prev_page_url: null,
    to: 5,
    total: 5,
};
